name: CSSAnimation

author: Ryan Florence

copyright: "&copy; [Ryan Florence](http://ryanflorence.com)"

license: MIT-style license.

sources:
  - "Source/CSSAnimation.js"
  - "Source/CSSAnimation.MooTools.js"
  - "Source/CSSAnimation.jQuery.js"